-- AlterTable
ALTER TABLE `episodes` MODIFY `status` ENUM('MISSING', 'QUEUED', 'DOWNLOADING', 'PAUSED', 'DOWNLOADED', 'ENCODING', 'COMPLETED', 'ERROR') NOT NULL DEFAULT 'MISSING';

-- AlterTable
ALTER TABLE `movies` MODIFY `status` ENUM('MISSING', 'QUEUED', 'DOWNLOADING', 'PAUSED', 'DOWNLOADED', 'ENCODING', 'COMPLETED', 'ERROR') NOT NULL DEFAULT 'MISSING';

-- AlterTable
ALTER TABLE `shows` MODIFY `status` ENUM('MISSING', 'QUEUED', 'DOWNLOADING', 'PAUSED', 'DOWNLOADED', 'ENCODING', 'COMPLETED', 'ERROR') NOT NULL DEFAULT 'MISSING';
